# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pK9MEd0W7CQphxOg42WUCaM1bnN5nzi2
"""

print('Hello Dunia!!!')
print('Belajar AI')
print('Yess!!')
